# 第二阶段：运行阶段
FROM alpine:latest
# 设置工作目录
RUN mkdir -p /root
WORKDIR /root/

# 从构建阶段复制二进制文件
COPY /bin/mhxy_helper_linux .
# 复制DB
COPY  mhxyhelper.db .
COPY  mhxyhelper.db-shm .
COPY  mhxyhelper.db-wal .

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN apk add --no-cache tzdata
ENV TZ Asia/Shanghai

# 设置编码
ENV LANG C.UTF-8

# 暴露端口
EXPOSE 8080

# 启动应用
CMD ["./mhxy_helper_linux"]